---
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
tasks:
  - init: |
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
      pre-commit install

vscode:
  extensions:
    - Vue.volar
    - EditorConfig.EditorConfig
    - davraamides.todotxt-mode
